/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Uyg;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;


public class Uygulama extends javax.swing.JFrame {

    String url = "http://www.haber7.com/";
    List<String> haberLink = new ArrayList<>();
    List<String> haberResim = new ArrayList<>();
    int calis = 1;


    public Uygulama() {
        initComponents();

        DefaultListModel dlm = new DefaultListModel<>();
        lstHaberKategori.setModel(dlm);
        lstManset.setModel(dlm);
        haberler();
    }

    public void haberler() {
        DefaultListModel dlm = new DefaultListModel<>();

        try {
            Document doc = Jsoup.connect(url).get();

            Elements uls = doc.getElementsByAttributeValue("id", "menu");
            Elements alt1 = uls.tagName("div").attr("class", "container");
            Elements alt2 = alt1.tagName("div").attr("class", "container-fluid");
            Elements alt3 = alt2.tagName("nav");
            Elements alt4 = alt3.tagName("ul");
            Elements alt5 = alt4.tagName("li");
            Elements alt6 = alt5.select("a");
            for (Element item : alt6) {
                String hk = item.attr("title");
                String adres = item.attr("href");

                if (!adres.contains("haber7.com")) {
                    haberLink.add("https://www.haber7.com" + adres);

                } else {

                    haberLink.add(adres);

                }

                dlm.addElement(hk);
                if (hk.equals("Medya Haberleri")) {
                    break;
                }
            }

        } catch (Exception e) {
            System.err.println("Hata : " + e);
        }
        lstHaberKategori.setModel(dlm);
    }

    public void mansetler() {
        DefaultListModel dlm = new DefaultListModel<>();
        try {
           
            Document doc = Jsoup.connect(url).get();
            
            Elements alt1 = doc.getElementsByAttributeValue("id", "headline");
            Elements alt2 = alt1.tagName("div").attr("class", "bx-wrapper");
            Elements alt3 = alt2.tagName("div").attr("class", "bx-viewport");
            Elements alt4 = alt3.tagName("ul").attr("class", "slider");
            Elements alt5 = alt4.tagName("li");
            Elements alt6 = alt5.select("a");
            for(int i=0;i<alt6.size();i++){
                String img;
                  String hk = alt6.get(i).attr("title");
              
                if(i==0){
                     img = alt6.get(i).getElementsByTag("img").attr("src");
                }else{
                    
                 img = alt6.get(i).getElementsByTag("img").attr("data-src");
                }
                img = img.trim();
                if (!img.equals("")) {
                    haberResim.add(img);
                }

                dlm.addElement(hk);
            }

        } catch (IOException ex) {
            System.err.println("Bağlantı Hatası :" + ex);
        }
        lstManset.setModel(dlm);
    }

    public void haberGoster() {
        txtHaberYazi.setText(lstManset.getSelectedValue());

        String urlResim = haberResim.get(lstManset.getSelectedIndex());
        try {
            URL ur = new URL(urlResim);
            BufferedImage img = ImageIO.read(ur);
            lblHaberResim.setIcon(new ImageIcon(img));
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstHaberKategori = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstManset = new javax.swing.JList<>();
        txtHaberYazi = new javax.swing.JTextField();
        lblHaberResim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Haber Kategorileri");

        jLabel2.setText("Manşetler");

        lstHaberKategori.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstHaberKategori.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstHaberKategoriValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstHaberKategori);

        lstManset.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstManset.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMansetValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstManset);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(txtHaberYazi)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 775, Short.MAX_VALUE))
                    .addComponent(lblHaberResim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHaberResim, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHaberYazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstHaberKategoriValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstHaberKategoriValueChanged
        if (calis % 2 == 1) {
            url = haberLink.get(lstHaberKategori.getSelectedIndex());
            //JOptionPane.showMessageDialog(this, url);
            haberResim.clear();
            mansetler();
        }
        calis++;
    }//GEN-LAST:event_lstHaberKategoriValueChanged

    private void lstMansetValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMansetValueChanged
        haberGoster();
    }//GEN-LAST:event_lstMansetValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uygulama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uygulama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uygulama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uygulama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uygulama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblHaberResim;
    private javax.swing.JList<String> lstHaberKategori;
    private javax.swing.JList<String> lstManset;
    private javax.swing.JTextField txtHaberYazi;
    // End of variables declaration//GEN-END:variables
}
